# fly.toml file generated for billowing-fog-6838 on 2021-07-11T00:28:32+08:00

app = "rustlangcc"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[experimental]
  cmd = "./rustlangcc"

# statics only serve files, not folders, and default serve index.html, otherwise 404
# [[statics]]
#   guest_path = "/"
#   url_prefix = "/root"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"
