# fly.toml file generated for rustlangcc on 2021-07-07T23:28:29+08:00

app = "rustlangcc"

kill_signal = "SIGINT"
kill_timeout = 5

# [build]
#   builtin = "static"

[experimental]
# required because we can't infer your binary's name
cmd = "./rustlangcc"

[env]
PORT = "8080"

# [experimental]
#   allowed_public_ports = []
#   auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"
